### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by miguelmartins17**
Add some information about dart how I'm working with Flutter and the Dart programming language is used.

### CODE REVIEW

**Comment by miguelmartins17** [comment]
Has anyone read this part I put on?
I'd like to know if it's good or missing for some information.

**Comment by iteles** [comment]
@miguelmartins17 Do you have permissions to add labels to pull requests or assign reviewers on this repo?

**Comment by miguelmartins17** [comment]
@iteles I don't think so.

**Comment by miguelmartins17** [comment]
@nelsonic Thanks, I'm doing my best. 🎉

**Pull request merged**
